// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.17.3
// source: memory-fuse.proto

package memoryfuse

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MemoryFuseService_Mount_FullMethodName      = "/memoryfuse.MemoryFuseService/Mount"
	MemoryFuseService_Unmount_FullMethodName    = "/memoryfuse.MemoryFuseService/Unmount"
	MemoryFuseService_ListMounts_FullMethodName = "/memoryfuse.MemoryFuseService/ListMounts"
	MemoryFuseService_Invalidate_FullMethodName = "/memoryfuse.MemoryFuseService/Invalidate"
)

// MemoryFuseServiceClient is the client API for MemoryFuseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Keep in sync with control-plane/proto/memory-fuse.proto.
// In-pod gRPC service exposed by the memory-fuse sidecar at :9102.
// cp pushes Mount/Unmount on live attachment changes; on pod boot the daemon
// pulls the initial attachment set from cp HTTP (no push needed for cold start).
//
// Mount path is /mnt/memory/<store_id>/ — using the store id directly keeps
// agent-visible paths stable across rename/re-attach and removes any
// slug-derivation logic.
type MemoryFuseServiceClient interface {
	Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*MountResponse, error)
	Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*UnmountResponse, error)
	ListMounts(ctx context.Context, in *ListMountsRequest, opts ...grpc.CallOption) (*ListMountsResponse, error)
	// Invalidate the daemon's in-memory snapshot + buf cache for a store.
	// cp pushes this fire-and-forget after every memory write/delete so each
	// attached workspace sees fresh data on the next read without waiting
	// for the 30s polling tick.
	Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error)
}

type memoryFuseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryFuseServiceClient(cc grpc.ClientConnInterface) MemoryFuseServiceClient {
	return &memoryFuseServiceClient{cc}
}

func (c *memoryFuseServiceClient) Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*MountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountResponse)
	err := c.cc.Invoke(ctx, MemoryFuseService_Mount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryFuseServiceClient) Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*UnmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmountResponse)
	err := c.cc.Invoke(ctx, MemoryFuseService_Unmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryFuseServiceClient) ListMounts(ctx context.Context, in *ListMountsRequest, opts ...grpc.CallOption) (*ListMountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMountsResponse)
	err := c.cc.Invoke(ctx, MemoryFuseService_ListMounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryFuseServiceClient) Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateResponse)
	err := c.cc.Invoke(ctx, MemoryFuseService_Invalidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryFuseServiceServer is the server API for MemoryFuseService service.
// All implementations must embed UnimplementedMemoryFuseServiceServer
// for forward compatibility
//
// Keep in sync with control-plane/proto/memory-fuse.proto.
// In-pod gRPC service exposed by the memory-fuse sidecar at :9102.
// cp pushes Mount/Unmount on live attachment changes; on pod boot the daemon
// pulls the initial attachment set from cp HTTP (no push needed for cold start).
//
// Mount path is /mnt/memory/<store_id>/ — using the store id directly keeps
// agent-visible paths stable across rename/re-attach and removes any
// slug-derivation logic.
type MemoryFuseServiceServer interface {
	Mount(context.Context, *MountRequest) (*MountResponse, error)
	Unmount(context.Context, *UnmountRequest) (*UnmountResponse, error)
	ListMounts(context.Context, *ListMountsRequest) (*ListMountsResponse, error)
	// Invalidate the daemon's in-memory snapshot + buf cache for a store.
	// cp pushes this fire-and-forget after every memory write/delete so each
	// attached workspace sees fresh data on the next read without waiting
	// for the 30s polling tick.
	Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error)
	mustEmbedUnimplementedMemoryFuseServiceServer()
}

// UnimplementedMemoryFuseServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMemoryFuseServiceServer struct {
}

func (UnimplementedMemoryFuseServiceServer) Mount(context.Context, *MountRequest) (*MountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mount not implemented")
}
func (UnimplementedMemoryFuseServiceServer) Unmount(context.Context, *UnmountRequest) (*UnmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unmount not implemented")
}
func (UnimplementedMemoryFuseServiceServer) ListMounts(context.Context, *ListMountsRequest) (*ListMountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMounts not implemented")
}
func (UnimplementedMemoryFuseServiceServer) Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invalidate not implemented")
}
func (UnimplementedMemoryFuseServiceServer) mustEmbedUnimplementedMemoryFuseServiceServer() {}

// UnsafeMemoryFuseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryFuseServiceServer will
// result in compilation errors.
type UnsafeMemoryFuseServiceServer interface {
	mustEmbedUnimplementedMemoryFuseServiceServer()
}

func RegisterMemoryFuseServiceServer(s grpc.ServiceRegistrar, srv MemoryFuseServiceServer) {
	s.RegisterService(&MemoryFuseService_ServiceDesc, srv)
}

func _MemoryFuseService_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryFuseServiceServer).Mount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryFuseService_Mount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryFuseServiceServer).Mount(ctx, req.(*MountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryFuseService_Unmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryFuseServiceServer).Unmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryFuseService_Unmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryFuseServiceServer).Unmount(ctx, req.(*UnmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryFuseService_ListMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryFuseServiceServer).ListMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryFuseService_ListMounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryFuseServiceServer).ListMounts(ctx, req.(*ListMountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryFuseService_Invalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryFuseServiceServer).Invalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryFuseService_Invalidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryFuseServiceServer).Invalidate(ctx, req.(*InvalidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryFuseService_ServiceDesc is the grpc.ServiceDesc for MemoryFuseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryFuseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memoryfuse.MemoryFuseService",
	HandlerType: (*MemoryFuseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mount",
			Handler:    _MemoryFuseService_Mount_Handler,
		},
		{
			MethodName: "Unmount",
			Handler:    _MemoryFuseService_Unmount_Handler,
		},
		{
			MethodName: "ListMounts",
			Handler:    _MemoryFuseService_ListMounts_Handler,
		},
		{
			MethodName: "Invalidate",
			Handler:    _MemoryFuseService_Invalidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memory-fuse.proto",
}
