apiVersion: apps/v1
kind: Deployment
metadata:
  name: nap-scheduler
  namespace: ${NAMESPACE}
  labels:
    app: nap-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nap-scheduler
  template:
    metadata:
      labels:
        app: nap-scheduler
    spec:
      containers:
        - name: scheduler
          image: ${REGISTRY}/nap-scheduler:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nap-pg-user
                  key: password
            - name: DATABASE_URL
              value: "postgresql://${PG_USERNAME}:$(POSTGRES_PASSWORD)@nap-pg-rw:5432/nap"
            - name: NAP_API_URL
              value: "http://nap-cp:3000"
            - name: CG_API_URL
              value: "http://nap-cg:3002"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
