apiVersion: v1
kind: Secret
metadata:
  name: nap-pg-user
  namespace: ${NAMESPACE}
type: kubernetes.io/basic-auth
stringData:
  username: ${PG_USERNAME}
  password: ${PG_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: nap-cp-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  CREDENTIAL_ENCRYPTION_KEY: "${CREDENTIAL_ENCRYPTION_KEY}"
  LDAP_URL: "${LDAP_URL}"
  LDAP_BIND_DN: "${LDAP_BIND_DN}"
  LDAP_BIND_PASSWORD: "${LDAP_BIND_PASSWORD}"
  LDAP_SEARCH_BASE: "${LDAP_SEARCH_BASE}"
  LDAP_SEARCH_FILTER: "${LDAP_SEARCH_FILTER}"
  LDAP_ATTR_USERNAME: "${LDAP_ATTR_USERNAME}"
  LDAP_ATTR_NAME: "${LDAP_ATTR_NAME}"
  LDAP_ATTR_EMAIL: "${LDAP_ATTR_EMAIL}"
---
apiVersion: v1
kind: Secret
metadata:
  name: nap-browser-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  JWT_SECRET: "${BROWSER_JWT_SECRET}"
  TURN_AUTH_SECRET: "${TURN_AUTH_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: nap-sandbox-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  JWT_SECRET: "${SANDBOX_JWT_SECRET}"
  SERVICE_KEY: "${SANDBOX_SERVICE_KEY}"
