{{- if not .Values.envToken.existingSecret -}}
{{- if not .Values.envToken.token -}}
{{- fail "envToken.token or envToken.existingSecret is required" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "env-runner-k8s.tokenSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "env-runner-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.envToken.secretKey }}: {{ .Values.envToken.token | quote }}
{{- end -}}
